//*****************************************************************************
//*****************************************************************************
//  FILENAME: GREEN.h
//   Version: 1.3, Updated on 2010/6/8 at 12:37:13                                          
//  Generated by PSoC Designer 5.4.2946
//
//  DESCRIPTION: GREEN User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2010. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef GREEN_INCLUDE
#define GREEN_INCLUDE

#include <m8c.h>


/* Create pragmas to support proper argument and return value passing */
#pragma fastcall16  GREEN_Stop
#pragma fastcall16  GREEN_Start
#pragma fastcall16  GREEN_On
#pragma fastcall16  GREEN_Off
#pragma fastcall16  GREEN_Switch
#pragma fastcall16  GREEN_Invert
#pragma fastcall16  GREEN_GetState


//-------------------------------------------------
// Constants for GREEN API's.
//-------------------------------------------------
//
#define  GREEN_ON   1
#define  GREEN_OFF  0

//-------------------------------------------------
// Prototypes of the GREEN API.
//-------------------------------------------------
extern void  GREEN_Start(void);                                     
extern void  GREEN_Stop(void);                                      
extern void  GREEN_On(void);                                      
extern void  GREEN_Off(void);                                      
extern void  GREEN_Switch(BYTE bSwitch);
extern void  GREEN_Invert(void);                                         
extern BYTE  GREEN_GetState(void);                                         

//-------------------------------------------------
// Define global variables.                 
//-------------------------------------------------



#endif
