//*****************************************************************************
//*****************************************************************************
//  FILENAME: RED.h
//   Version: 1.3, Updated on 2010/6/8 at 12:37:13                                          
//  Generated by PSoC Designer 5.4.2946
//
//  DESCRIPTION: RED User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2010. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef RED_INCLUDE
#define RED_INCLUDE

#include <m8c.h>


/* Create pragmas to support proper argument and return value passing */
#pragma fastcall16  RED_Stop
#pragma fastcall16  RED_Start
#pragma fastcall16  RED_On
#pragma fastcall16  RED_Off
#pragma fastcall16  RED_Switch
#pragma fastcall16  RED_Invert
#pragma fastcall16  RED_GetState


//-------------------------------------------------
// Constants for RED API's.
//-------------------------------------------------
//
#define  RED_ON   1
#define  RED_OFF  0

//-------------------------------------------------
// Prototypes of the RED API.
//-------------------------------------------------
extern void  RED_Start(void);                                     
extern void  RED_Stop(void);                                      
extern void  RED_On(void);                                      
extern void  RED_Off(void);                                      
extern void  RED_Switch(BYTE bSwitch);
extern void  RED_Invert(void);                                         
extern BYTE  RED_GetState(void);                                         

//-------------------------------------------------
// Define global variables.                 
//-------------------------------------------------



#endif
