//*****************************************************************************
//*****************************************************************************
//  FILENAME: BLUE.h
//   Version: 1.3, Updated on 2010/6/8 at 12:37:13                                          
//  Generated by PSoC Designer 5.4.2946
//
//  DESCRIPTION: BLUE User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2010. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef BLUE_INCLUDE
#define BLUE_INCLUDE

#include <m8c.h>


/* Create pragmas to support proper argument and return value passing */
#pragma fastcall16  BLUE_Stop
#pragma fastcall16  BLUE_Start
#pragma fastcall16  BLUE_On
#pragma fastcall16  BLUE_Off
#pragma fastcall16  BLUE_Switch
#pragma fastcall16  BLUE_Invert
#pragma fastcall16  BLUE_GetState


//-------------------------------------------------
// Constants for BLUE API's.
//-------------------------------------------------
//
#define  BLUE_ON   1
#define  BLUE_OFF  0

//-------------------------------------------------
// Prototypes of the BLUE API.
//-------------------------------------------------
extern void  BLUE_Start(void);                                     
extern void  BLUE_Stop(void);                                      
extern void  BLUE_On(void);                                      
extern void  BLUE_Off(void);                                      
extern void  BLUE_Switch(BYTE bSwitch);
extern void  BLUE_Invert(void);                                         
extern BYTE  BLUE_GetState(void);                                         

//-------------------------------------------------
// Define global variables.                 
//-------------------------------------------------



#endif
